# Generated by Django 5.1.3 on 2024-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_remove_part_value_part_diameter_part_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.IntegerField(default=52),
        ),
    ]
